// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthenticateQRLogin(arg1:string,arg2:string,arg3:string):Promise<main.Response>;

export function CheckQRLoginStatus(arg1:string):Promise<main.Response>;

export function ConfirmSensorSubmission(arg1:string,arg2:number):Promise<main.Response>;

export function GenerateQRLoginCode():Promise<main.Response>;

export function GetCurrentUser():Promise<main.Response>;

export function GetSensorReading():Promise<main.Response>;

export function GetSubmissions():Promise<main.Response>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:main.LoginRequest):Promise<main.Response>;

export function Logout():Promise<main.Response>;

export function Register(arg1:main.RegisterRequest):Promise<main.Response>;

export function StartSensorScan():Promise<main.Response>;

export function SubmitTrash(arg1:main.SubmissionRequest):Promise<main.Response>;
