// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateQRLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthenticateQRLogin'](arg1, arg2, arg3);
}

export function CheckQRLoginStatus(arg1) {
  return window['go']['main']['App']['CheckQRLoginStatus'](arg1);
}

export function ConfirmSensorSubmission(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSensorSubmission'](arg1, arg2);
}

export function GenerateQRLoginCode() {
  return window['go']['main']['App']['GenerateQRLoginCode']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetSensorReading() {
  return window['go']['main']['App']['GetSensorReading']();
}

export function GetSubmissions() {
  return window['go']['main']['App']['GetSubmissions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function StartSensorScan() {
  return window['go']['main']['App']['StartSensorScan']();
}

export function SubmitTrash(arg1) {
  return window['go']['main']['App']['SubmitTrash'](arg1);
}
