// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSessionStatus() {
  return window['go']['main']['App']['CheckSessionStatus']();
}

export function ConfirmSensorSubmission(arg1, arg2) {
  return window['go']['main']['App']['ConfirmSensorSubmission'](arg1, arg2);
}

export function EndSession() {
  return window['go']['main']['App']['EndSession']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetSensorReading() {
  return window['go']['main']['App']['GetSensorReading']();
}

export function GetSubmissions() {
  return window['go']['main']['App']['GetSubmissions']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RequestSessionToken() {
  return window['go']['main']['App']['RequestSessionToken']();
}

export function StartSensorScan() {
  return window['go']['main']['App']['StartSensorScan']();
}

export function SubmitTrash(arg1) {
  return window['go']['main']['App']['SubmitTrash'](arg1);
}

export function VerifyAndConnectSession(arg1, arg2) {
  return window['go']['main']['App']['VerifyAndConnectSession'](arg1, arg2);
}
